# Project identification
sonar.projectKey=SWESS26_G1T4
sonar.projectName=SWESS26_G1T4
sonar.qualitygate.wait=true

# Source/Test directories
sonar.sources=webapp/src/main/frontend,webapp/src/main/java,raspberrypi/app
sonar.tests=webapp/src/test/java,raspberrypi/tests
sonar.coverage.exclusions=webapp/src/main/frontend/**

# Binaries
sonar.java.binaries=webapp/target/classes
sonar.java.test.binaries=webapp/target/test-classes

# Libraries
sonar.java.libraries=webapp/target/dependency/**/*.jar
sonar.java.test.libraries=webapp/target/dependency/**/*.jar

# Python specifics and coverage report 
sonar.python.version=3.12
sonar.python.coverage.reportPaths=raspberrypi/coverage.xml

# Jacoco Coverage Report
sonar.coverage.jacoco.xmlReportPaths=webapp/target/site/jacoco/jacoco.xml
