services:
  gateway:
    build: ./app
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /home/pi/data:/home/pi/data
      - /home/pi/logs:/home/pi/logs
      - /home/pi/conf.yaml:/app/conf.yaml:ro
