package at.qe.skeleton.model;

public enum Permission {
    CAN_VIEW_OWN_OFFICE_CLIMATE,
    CAN_VIEW_OWN_SHARED_CLIMATE,
    CAN_VIEW_OWN_OFFICE_WARNINGS,
    CAN_MANAGE_OWN_ABSENCE,
    CAN_VIEW_OWN_DEPARTMENT_MEASURES,
    CAN_VIEW_OWN_DEPARTMENT_WARNINGS,
    CAN_VIEW_ABSENCE_VIEW,
    CAN_MANAGE_ABSENCES,
    CAN_VIEW_COMPANY_AGGR,
    CAN_VIEW_VIOLATIONS_PER_DEPARTMENT,
    CAN_CHANGE_LIMITS,
    CAN_MANAGE_TIPS,
    CAN_VIEW_ALL_ROOMS,
    CAN_VIEW_ALL_BUILDINGS,
    CAN_MANAGE_USERS,
    CAN_MANAGE_BUILDING_STRUCTURE,
    CAN_MANAGE_DEVICES,
    CAN_GET_RASPBERRY_CONFIG,
    CAN_VIEW_OCCUPANCY,
    CAN_SEND_WARNINGS,
    CAN_SEND_MEASUREMENTS,
    CAN_LIMITED_MANAGE_DEVICES
}
