system:
  environment: "production"
  
paths:
  database: "/home/pi/data/production.sqlite"
  log_file: "/home/pi/logs/raspberrypi.log"

ble:
  target_name: "SensorStation"
  char_uuid: "19B10001-E8F2-537E-4F6C-D104768A1214"
  write_uuid: "19B10002-E8F2-537E-4F6C-D104768A1214"

webapp:
  api_url: "http://192.168.178.33:8080/measurements"
  local_listen_port: 8080
