export const ROUTES = {
    HOME: '/',
    MANAGE_USERS: '/manage-users',
    LOGIN: '/login',
    LOGOUT: '/logout',
    EMPLOYEE_DASHBOARD: '/employee-dashboard',
    SYSADMIN_DASHBOARD: '/sysadmin-dashboard',
    SENIOR_MANAGER_DASHBOARD: '/senior-manager-dashboard',
    DEPARTMENT_MANAGER_DASHBOARD: '/department-manager-dashboard',
    BUILDING_MANAGER_DASHBOARD: '/building-manager-dashboard',
    DEVICE_CONFIGURATION: '/device-configuration',
    USER_CONFIGURATION: '/user-configuration',
    BUILDING_CONFIGURATION: '/building-configuration',
    EMPLOYEE_ABSENCES: '/employee-absences',
    DEPARTMENT_ABSENCES: '/department-absences',
    EMPLOYEE_DEPARTMENT: '/my-department',
    SETTINGS: '/settings',
    DEPARTMENT_DETAIL: '/senior/department/:departmentName',
    BUILDING_ROOM_ANALYSIS: '/building-room-analysis/:roomId',
    TIPMANAGEMENT: '/tipmanagement',
    MY_ROOM: '/my-room',
    COMPANY_TRENDS: '/senior/trends',
    DEPARTMENT_VIOLATIONS: '/department-violations',
    ROOM_DETAIL: '/department/room/:roomId',
    NOT_FOUND: '/404',
    FORBIDDEN: '/403',
} as const;