export const ROUTES = {
    HOME: '/',
    MANAGE_USERS: '/manage-users',
    LOGIN: '/login',
    LOGOUT: '/logout',
    EMPLOYEE_DASHBOARD: '/employee-dashboard',
    DEVICE_CONFIGURATION: '/device-configuration',
    USER_CONFIGURATION: '/user-configuration',
    BUILDING_CONFIGURATION: '/building-configuration',
    EMPLOYEE_ABSENCES: '/employee-absences',
    DEPARTMENT_ABSENCES: '/department-absences',
    EMPLOYEE_DEPARTMENT: '/my-department',
    SETTINGS: '/settings',
    DEPARTMENT_DETAIL: '/senior/department/:departmentName',
    BUILDING_ROOM_ANALYSIS: '/building-room-analysis/:roomId',
    TIPMANAGEMENT: '/tipmanagement',
    MY_ROOM: '/my-room',
} as const;